/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: {
          DEFAULT: 'rgb(var(--surface) / <alpha-value>)',
          raised: 'rgb(var(--surface-raised) / <alpha-value>)',
          sunken: 'rgb(var(--surface-sunken) / <alpha-value>)',
          hover: 'rgb(var(--surface-hover) / <alpha-value>)',
          hover2: 'rgb(var(--surface-hover2) / <alpha-value>)',
        },
        line: {
          DEFAULT: 'rgb(var(--line) / <alpha-value>)',
          soft: 'rgb(var(--line-soft) / <alpha-value>)',
          strong: 'rgb(var(--line-strong) / <alpha-value>)',
          key: 'rgb(var(--line-key) / <alpha-value>)',
          hover: 'rgb(var(--line-hover) / <alpha-value>)',
        },
        ink: {
          DEFAULT: 'rgb(var(--ink) / <alpha-value>)',
          bright: 'rgb(var(--ink-bright) / <alpha-value>)',
          mid: 'rgb(var(--ink-mid) / <alpha-value>)',
          dim: 'rgb(var(--ink-dim) / <alpha-value>)',
          faint: 'rgb(var(--ink-faint) / <alpha-value>)',
        },
        accent: 'rgb(var(--accent) / <alpha-value>)',
        'accent-hi': 'rgb(var(--accent-hi) / <alpha-value>)',
        'accent-wash': 'rgb(var(--accent-wash) / <alpha-value>)',
        correct: 'rgb(var(--correct) / <alpha-value>)',
        'correct-wash': 'rgb(var(--correct-wash) / <alpha-value>)',
        wrong: 'rgb(var(--wrong) / <alpha-value>)',
        'wrong-wash': 'rgb(var(--wrong-wash) / <alpha-value>)',
        'on-accent': 'rgb(var(--on-accent) / <alpha-value>)',
        background: 'rgb(var(--surface) / <alpha-value>)',
        foreground: 'rgb(var(--ink) / <alpha-value>)',
        card: 'rgb(var(--surface-raised) / <alpha-value>)',
        'card-foreground': 'rgb(var(--ink) / <alpha-value>)',
        popover: 'rgb(var(--surface-raised) / <alpha-value>)',
        'popover-foreground': 'rgb(var(--ink) / <alpha-value>)',
        muted: 'rgb(var(--surface-sunken) / <alpha-value>)',
        'muted-foreground': 'rgb(var(--ink-dim) / <alpha-value>)',
        border: 'rgb(var(--line) / <alpha-value>)',
        input: 'rgb(var(--line-strong) / <alpha-value>)',
        ring: 'rgb(var(--accent) / <alpha-value>)',
        primary: 'rgb(var(--accent) / <alpha-value>)',
        'primary-foreground': 'rgb(var(--on-accent) / <alpha-value>)',
        secondary: 'rgb(var(--surface-hover) / <alpha-value>)',
        'secondary-foreground': 'rgb(var(--ink) / <alpha-value>)',
        destructive: 'rgb(var(--wrong) / <alpha-value>)',
        'destructive-foreground': 'rgb(var(--on-accent) / <alpha-value>)',
      },
      fontFamily: {
        sans: ['"Inter Tight"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'SFMono-Regular', 'monospace'],
      },
      fontSize: {
        eyebrow: ['0.6875rem', { lineHeight: '1.4', letterSpacing: '0.14em' }],
        stem: ['clamp(1.25rem, 2.7vw, 1.5625rem)', { lineHeight: '1.4', letterSpacing: '-0.018em' }],
        h1: ['clamp(1.6875rem, 4.2vw, 2.375rem)', { lineHeight: '1.12', letterSpacing: '-0.025em' }],
        score: ['clamp(2.5rem, 7vw, 3.625rem)', { lineHeight: '1', letterSpacing: '-0.035em' }],
      },
      borderRadius: { card: '5px', chip: '3px' },
      maxWidth: { shell: '920px', quiz: '840px' },
      keyframes: {
        fadeUp: { from: { opacity: '0', transform: 'translateY(7px)' }, to: { opacity: '1', transform: 'none' } },
        fadeIn: { from: { opacity: '0' }, to: { opacity: '1' } },
      },
      animation: {
        fadeUp: 'fadeUp .24s ease both',
        fadeIn: 'fadeIn .16s ease both',
      },
    },
  },
  plugins: [],
};
